#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.5-variegata
    with:
      extension_name: httpfs
      duckdb_version: 07a8585ad613bfa0f3026a58d879bc0bd945d812
      ci_tools_version: v1.5-variegata

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@v1.5-variegata
    secrets: inherit
    with:
      extension_name: httpfs
      duckdb_version: 07a8585ad613bfa0f3026a58d879bc0bd945d812
      ci_tools_version: v1.5-variegata
      deploy_latest: ${{ startsWith(github.ref, 'refs/heads/v') }}
      deploy_versioned: ${{ startsWith(github.ref, 'refs/heads/v') || github.ref == 'refs/heads/main' }}

  duckdb-binary-build:
    name: Build DuckDB binary with httpfs
    runs-on: ${{ matrix.runner }}
    env:
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      VCPKG_OVERLAY_PORTS: ${{ github.workspace }}/extension-ci-tools/vcpkg_ports
      VCPKG_OVERLAY_TRIPLETS: ${{ github.workspace }}/extension-ci-tools/toolchains
      GEN: ninja
    strategy:
      matrix:
        arch: [osx_arm64, linux_amd64]
        include:
          - arch: osx_arm64
            runner: macos-14
            vcpkg_triplet: arm64-osx
          - arch: linux_amd64
            runner: ubuntu-latest
            vcpkg_triplet: x64-linux
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - uses: actions/checkout@v4
        name: Checkout Extension CI tools
        with:
          path: 'extension-ci-tools'
          ref: v1.5-variegata
          repository: duckdb/extension-ci-tools

      - name: Checkout DuckDB to version
        run: |
          DUCKDB_GIT_VERSION=07a8585ad613bfa0f3026a58d879bc0bd945d812 make set_duckdb_version

      - name: Install Ninja (macOS)
        if: runner.os == 'macOS'
        run: brew install ninja

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y ninja-build libssl-dev libcurl4-openssl-dev

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          git checkout 84bab45d415d22042bd0b9081aea57f362da3f35
          ./bootstrap-vcpkg.sh

      - name: Build
        env:
          VCPKG_TARGET_TRIPLET: ${{ matrix.vcpkg_triplet }}
          USE_MERGED_VCPKG_MANIFEST: 1
        run: |
          BUILD_SHELL=1 make release

      - uses: actions/upload-artifact@v4
        with:
          name: duckdb-binary-${{ matrix.arch }}
          path: build/release/duckdb
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: duckdb-extensions-${{ matrix.arch }}
          path: |
            build/release/extension/**/aws.duckdb_extension
            build/release/extension/**/avro.duckdb_extension
            build/release/extension/**/httpfs.duckdb_extension
            build/release/extension/**/iceberg.duckdb_extension
          if-no-files-found: error

  code-quality:
    name: Code Quality
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_code_quality.yml@v1.5-variegata
    with:
      extension_name: httpfs
      duckdb_version: 07a8585ad613bfa0f3026a58d879bc0bd945d812
      ci_tools_version: v1.5-variegata
      extra_toolchains: 'python3'
      format_checks: 'format'
